# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-04346197d63f4b91ba0e315795a739dc
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      strict-json-schema: true
      response-format: json_object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-04346197d63f4b91ba0e315795a739dc
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true

